inherit_from:
  - ~/.rubocop.yml

AllCops:
  Exclude:
    - 'test/tmp/**/*'
    - 'vendor/bundle/**/*'

Style/MethodCallWithArgsParentheses:
  Exclude:
    - '**/Gemfile'
    - '*_spec.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'
