inherit_from:
  - ~/.rubocop.yml

AllCops:
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
  Exclude:
    - 'test/tmp/**/*'
    - 'vendor/bundle/**/*'

Style/MethodCallWithArgsParentheses:
  Exclude:
    - '**/Gemfile'
    - '*_spec.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Naming/VariableName:
  Enabled: false

RSpec/VariableName:
  Enabled: false
