# Inherit the shared config from the rubocop-ddoherty gem (git-hosted on GitHub)
inherit_gem:
  rubocop-ddoherty: 'config/default.yml'

AllCops:
  Include:
    - 'lib/**/*'
    - 'spec/**/*'
  Exclude:
    - 'test/tmp/**/*'
    - 'vendor/bundle/**/*'

Style/MethodCallWithArgsParentheses:
  Exclude:
    - '**/Gemfile'
    - '*_spec.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/**/*'

Naming/VariableName:
  Enabled: false

RSpec/VariableName:
  Enabled: false
