require 'fat_table/formatters/formatter'
require 'fat_table/formatters/aoa_formatter'
require 'fat_table/formatters/aoh_formatter'
require 'fat_table/formatters/org_formatter'
require 'fat_table/formatters/text_formatter'
require 'fat_table/formatters/term_formatter'
require 'fat_table/formatters/latex_formatter'
